title: mrry.github.io
author: 
  name: Derek Murray
google_analytics: UA-89610241-1

show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: mrry
    github:  mrry
    stackoverflow: "3574081"
    linkedin: derekmurray

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
