title: mrry.github.io
author: Derek Murray
  
description: Derek Murray's personal site

google_analytics: UA-89610241-1

show_excerpts: false

twitter_username: mrry
github_username: mrry
linkedin_username: derekmurray

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
